### PR TITLE
Accounts

### PR DESCRIPTION
**Pull request by hugoroussel**
**What this PR does**
Simplify the simulation of coins.go by creating helper function to spawn, credit and check balance. Add accounts as a parameter of coins.toml. 

*See commit message*
This PR 

---

🙅‍ Friendly checklist:

- [ ] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [ ] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [ ] 2. Any new behaviour is tested and small units of code that can be are unit tested.
- [ ] 3. Code comments are added on tests to explain what they do.
- [ ] 4. Errors are systematically wrapped with a meaningful message using `xerrors.Errorf` and the `%v` verb.
- [ ] 5. Hard limit of 80 chars is always respected.
- [ ] 6. Changes are backward compatible.
- [ ] 7. Indentation level does not exceed 5, although 4 is already suspicious.
- [ ] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [ ] 9. There are no magic values.

### CODE REVIEW

**Comment by ineiti** [comment]
Hey - travis should pass when you do PRs!

**Comment by louismerlin** [comment]
Sorry !

It seems that our issue lies with the coveralls login token, do you know how we could fix it ? Do we need to register the repo inside the site ?

https://github.com/lemurheavy/coveralls-public/issues/632

**Comment by ineiti** [comment]
Ah, good point. I cleaned up the `.travis.yml` a bit - this should work: #2 - I also removed the `.ts` and java-tests, as well as the deployment. You don't need those for the moment.

**Comment by louismerlin** [comment]
Thanks a lot !

**Pull request merged**
